apiVersion: v1
kind: Service
metadata:
  name: autodeploy4433
  namespace: namespace-workflow-1719578594142
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy4433
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000